"Mobs Run Away From Wilted (default: true)" = true
"Strong Mobs Don't Run Away From Wilted (default: true)" = true
"Wilted Adds Cooldowns To Nearby Light Items (default: true)" = false
"Wilted Disables Nearby Dynamic Lights (default: true)" = false
"Tamed Wolves Attack Wilted (default: true)" = false
"Wilted Prevents Portal Travel (default: true)" = true
"Wilted Immune To Damage (default: true)" = true
"Wilted First Spawn Day (default: 1)" = 1
"Minimum Wilted Spawn Cooldown (in days, default: false)" = 1
"Maximum Wilted Spawn Cooldown (in days, default: false)" = 1
"Wilted Bonus Behaviour Amount (default: 3)" = 3
"Wilted Spawn Dimensions (default: \"minecraft:overworld\")" = ["minecraft:the_nether"]
"Wilted Warning Sounds (default: true)" = true

