
[Temperature]
	#Add heat stroke effect in summer noon while in hot biome.
	HeatStroke = false

[Season]
	#The lasting days of each term, while 4 seasons in 1 year, 6 terms in 1 season.
	#Range: 1 ~ 5000
	LastingDaysOfEachTerm = 7
	#The index of the initial solar term, and note it only can be used to first start the world with the mod.
	#Range: 1 ~ 24
	InitialSolarTermIndex = 1
	#Enable solar term change inform.
	EnableInform = false
	#Whether send inform with icon.
	EnableInformIcon = true
	#Whether to pop up the solar term reminder when the calendar item cannot be placed.
	CalendarItemHint = false
	#In summer, the days are long and the nights are short, while in winter, the days are short and the nights are long.
	DynamicDaylightDuration = true
	#Which dimensions will have season effects? Note that it must be natrual and have time lapse.
	ValidDimensions = ["minecraft:overworld"]

[Debug]
	#Enable debug option to detect illegal use of functions.
	LogIllegalUse = false
	#Without snowy block under the light blocks which level is 0.
	NotSnowyUnderLight0 = false
	#Enables legacy mode for snow and ice, where snow accumulates when it's cold in snowy day and melts when it's hot.
	LegacySnowAndMelt = false
	#Snow overlay block if has full collision shape not just full render shape.
	SnowyFullCollisionShape = false
	#Snow can cover the block which would lights.
	NotSnowOverlayGlowingBlock = false

[Weather]
	#Enable solar term weather system with biome.
	UseSolarWeather = true
	#Set the percentage multiplier of the probability of rain, the range should be between 0 and 1000.
	#Range: 0 ~ 1000
	RainChancePercentMultiplier = 60
	#Set the percentage multiplier of the probability of thunder in the rain, the range should be between 0 and 1000.
	#Range: 0 ~ 1000
	ThunderChancePercentMultiplier = 80

[Crop]
	#Enable crop season control.
	EnableSeasonalCrop = true
	#How much chance can crop grow in wrong season.
	#Range: 0.0 ~ 1.0
	CropGrowChanceInWrongSeason = 0.25
	#Enable crop humidity control.
	EnableCropHumidityControl = true
	#If a crop is not registered for a season or humid type, default values will be used.
	RegisterCropDefaultValue = false

[Compat]
	#Compatible with mods using SereneSeasons' CropTag.
	SereneSeasonsCropTag = true

