
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Don't touch unless you are told to
	debug_packet = false
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	#Disables certain types
	[general.types]

		[general.types.wood_type]

			[general.types.wood_type.mynethersdelight]
				powdery = true

			[general.types.wood_type.habitat]
				fairy_ring_mushroom = true

			[general.types.wood_type.ecologics]
				flowering_azalea = true
				azalea = true
				coconut = true
				walnut = true

			[general.types.wood_type.quark]
				azalea = true
				ancient = true
				blossom = true

			[general.types.wood_type.goodending]
				muddy_oak = true
				cypress = true

			[general.types.wood_type.biomesoplenty]
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.wood_type.phantasm]
				pream = true

			[general.types.wood_type.born_in_chaos_v1]
				scorched = true

			[general.types.wood_type.upgrade_aquatic]
				driftwood = true
				river = true

			[general.types.wood_type.alexscaves]
				pewen = true
				thornwood = true

			[general.types.wood_type.regions_unexplored]
				alpha = true
				baobab = true
				blackwood = true
				blue_bioshroom = true
				brimwood = true
				cobalt = true
				cypress = true
				dead = true
				eucalyptus = true
				green_bioshroom = true
				joshua = true
				kapok = true
				larch = true
				magnolia = true
				maple = true
				mauve = true
				palm = true
				pine = true
				pink_bioshroom = true
				redwood = true
				socotra = true
				willow = true
				yellow_bioshroom = true

			[general.types.wood_type.spawn]
				rotten = true

			[general.types.wood_type.outer_end]
				azure = true

			[general.types.wood_type.environmental]
				willow = false
				pine = true
				plum = true
				wisteria = true

			[general.types.wood_type.atmospheric]
				rosewood = true
				morado = true
				yucca = true
				aspen = true
				laurel = true
				kousa = true
				grimwood = true

			[general.types.wood_type.cataclysm]
				chorus = true

			[general.types.wood_type.endergetic]
				poise = true

			[general.types.wood_type.deeperdarker]
				echo = true

		[general.types.leaves_type]

			[general.types.leaves_type.biomesoplenty]
				origin = true
				flowering_oak = true
				maple = true
				orange_autumn = true
				yellow_autumn = true
				rainbow_birch = true
				snowblossom = true
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.leaves_type.regions_unexplored]
				bamboo = true
				golden_larch = true
				alpha = true
				apple_oak = true
				baobab = true
				blackwood = true
				magnolia = true
				cypress = true
				dead = true
				dead_pine = true
				eucalyptus = true
				flowering = true
				kapok = true
				larch = true
				maple = true
				mauve = true
				orange_maple = true
				palm = true
				pine = true
				blue_magnolia = true
				pink_magnolia = true
				redwood = true
				red_maple = true
				brimwood = true
				enchanted_birch = true
				small_oak = true
				silver_birch = true
				socotra = true
				white_magnolia = true
				willow = true
				ashen = true

			[general.types.leaves_type.goodending]
				cypress = true
				dense_birch = true
				dense_dark_oak = true

			[general.types.leaves_type.ecologics]
				coconut = true
				walnut = true

			[general.types.leaves_type.phantasm]
				pream = true

			[general.types.leaves_type.upgrade_aquatic]
				river = true

			[general.types.leaves_type.alexscaves]
				ancient = true

			[general.types.leaves_type.quark]
				ancient = true
				blue_blossom = true
				lavender_blossom = true
				orange_blossom = true
				yellow_blossom = true
				red_blossom = true

			[general.types.leaves_type.outer_end]
				azure = true

			[general.types.leaves_type.environmental]
				hibiscus = true
				willow = false
				pine = true
				plum = true
				cheerful_plum = true
				moody_plum = true
				wisteria = true
				pink_wisteria = true
				blue_wisteria = true
				purple_wisteria = true
				white_wisteria = true

			[general.types.leaves_type.atmospheric]
				rosewood = true
				morado = true
				flowering_morado = true
				yucca = true
				aspen = true
				green_aspen = true
				laurel = true
				dry_laurel = true
				kousa = true
				currant = true
				grimwood = true

			[general.types.leaves_type.deeperdarker]
				echo = true

		[general.types.cake]

			[general.types.cake.neapolitan]
				vanilla_cake = true
				chocolate_cake = true
				strawberry_cake = true
				banana_cake = true
				mint_cake = true
				adzuki_cake = true

			[general.types.cake.seasonals]
				pumpkin_cake = true
				sweet_berry_cake = true
				beetroot_cake = true

	#Disables specific entries
	[general.entries]

		[general.entries.wood_type]

			[general.entries.wood_type.quark]
				vertical_planks = true
				post = true
				trapped_chest = true
				bookshelf = true
				chest = true
				stripped_post = true
				ladder = true
				hollow_log = true

			[general.entries.wood_type.another_furniture]
				table = true
				flower_box = true
				shelf = true
				drawer = true
				shutter = true
				bench = true
				chair = true

			[general.entries.wood_type.regions_unexplored]
				branch = true

			[general.entries.wood_type.create]
				window = true
				window_pane = true

			[general.entries.wood_type.farmersdelight]
				cabinet = true

			[general.entries.wood_type.missingwilds]
				fallen_log = true

			[general.entries.wood_type.hearth_and_home]
				lattice = true
				parquet = true
				vertical_trim = true
				trim = true
				sanded_wood = true

		[general.entries.leaves_type]

			[general.entries.leaves_type.quark]
				hedge = true
				leaf_carpet = true

