
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.habitat]
			fairy_ring_mushroom = true

		[types.wood_type.ecologics]
			flowering_azalea = false
			azalea = false
			coconut = true
			walnut = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.biomesoplenty]
			fir = false
			redwood = false
			mahogany = true
			jacaranda = true
			palm = false
			willow = false
			dead = false
			magic = true
			umbran = true
			hellbark = true
			pine = true
			maple = true
			empyreal = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.outer_end]
			azure = true

		[types.wood_type.endergetic]
			poise = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = false
			wisteria = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.regions_unexplored]
			alpha = false
			baobab = true
			blackwood = false
			blue_bioshroom = true
			brimwood = true
			cobalt = true
			cypress = false
			dead = false
			eucalyptus = true
			green_bioshroom = true
			joshua = true
			kapok = false
			larch = false
			magnolia = true
			maple = true
			mauve = true
			palm = false
			pine = false
			pink_bioshroom = true
			redwood = true
			socotra = true
			willow = false
			yellow_bioshroom = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = false
			laurel = false
			kousa = true
			grimwood = true

		[types.wood_type.bloomingnature]
			larch = true
			baobab = false
			swamp_oak = true
			aspen = true
			fan_palm = false
			fir = true
			swamp_cypress = true
			ebony = true
			chestnut = true

		[types.wood_type.netherexp]
			claret = true

		[types.wood_type.sullysmod]
			petrified = true

	[types.leaves_type]

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			rainbow_birch = true
			snowblossom = true
			fir = false
			redwood = false
			mahogany = true
			jacaranda = true
			palm = false
			willow = false
			dead = false
			magic = true
			umbran = true
			hellbark = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			null = true
			cypress = true
			pine = true
			empyreal = true

		[types.leaves_type.regions_unexplored]
			bamboo = true
			golden_larch = false
			alpha = false
			apple_oak = true
			baobab = true
			blackwood = false
			magnolia = true
			cypress = false
			dead = true
			dead_pine = false
			eucalyptus = true
			flowering = true
			kapok = false
			larch = false
			maple = true
			mauve = true
			orange_maple = true
			palm = false
			pine = false
			blue_magnolia = true
			pink_magnolia = true
			redwood = true
			red_maple = true
			brimwood = true
			enchanted_birch = true
			small_oak = true
			silver_birch = true
			socotra = true
			white_magnolia = true
			willow = false
			ashen = true

		[types.leaves_type.outer_end]
			azure = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.environmental]
			hibiscus = true
			willow = true
			pine = true
			plum = false
			cheerful_plum = false
			moody_plum = false
			wisteria = true
			pink_wisteria = false
			blue_wisteria = false
			purple_wisteria = false
			white_wisteria = false

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = false
			green_aspen = false
			laurel = false
			dry_laurel = false
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.bloomingnature]
			larch = true
			baobab = true
			orange = true
			swamp_oak = true
			aspen = true
			fan_palm = true
			swamp_cypress = true
			ebony = true
			chestnut = true

	[types.cake]

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.cake.seasonals]
			pumpkin_cake = true
			sweet_berry_cake = true
			beetroot_cake = true

		[types.cake.mynethersdelight]
			magma_cake = true

		[types.cake.exquisito]
			chorus_cake = true
			ether_bulb_cake = true
			jelly_ring_cake = true
			nightshade_berry_cake = true
			zure_berry_cake = true

	[types.cut_block_type]

		[types.cut_block_type.habitat]
			fairy_ring_mushroom = true

		[types.cut_block_type.immersive_weathering]
			mossy_brick = true
			mossy_stone = true
			snowy_stone = true
			snowy_cobblestone = true
			snowy_stone_brick = true
			sandy_stone = true
			sandy_cobblestone = true
			sandy_stone_brick = true
			cracked_brick = true
			cracked_end_stone_brick = true
			cracked_prismarine_brick = true
			charred = true
			cut_iron = true
			exposed_cut_iron = true
			weathered_cut_iron = true
			rusted_cut_iron = true
			waxed_cut_iron = true
			waxed_exposed_cut_iron = true
			waxed_weathered_cut_iron = true
			waxed_rusted_cut_iron = true
			plate_iron = true
			exposed_plate_iron = true
			weathered_plate_iron = true
			rusted_plate_iron = true
			waxed_plate_iron = true
			waxed_exposed_plate_iron = true
			waxed_weathered_plate_iron = true
			waxed_rusted_plate_iron = true

		[types.cut_block_type.biomesoplenty]
			white_sandstone = true
			smooth_white_sandstone = true
			cut_white_sandstone = true
			orange_sandstone = true
			smooth_orange_sandstone = true
			cut_orange_sandstone = true
			black_sandstone = true
			smooth_black_sandstone = true
			cut_black_sandstone = true
			brimstone_brick = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			pine = true
			maple = true
			empyreal = true

		[types.cut_block_type.galosphere]
			silver_tiles = true
			silver_panel = true
			smooth_amethyst = true
			smooth_allurite = true
			smooth_lumiere = true
			amethyst_brick = true
			allurite_brick = true
			lumiere_brick = true
			pink_salt = true
			rose_pink_salt = true
			pastel_pink_salt = true
			polished_pink_salt = true
			polished_rose_pink_salt = true
			polished_pastel_pink_salt = true
			pink_salt_brick = true
			rose_pink_salt_brick = true
			pastel_pink_salt_brick = true

		[types.cut_block_type.absentbydesign]
			end_stone = true
			netherrack = true
			snow = true
			bricks_cracked = true
			coarse_dirt = true
			obsidian = true
			basalt = true
			polished_basalt = true
			crying_obsidian = true
			lodestone = true
			quartz_bricks = true
			glowstone = true
			sea_lantern = true
			black_concrete = true
			blue_concrete = true
			brown_concrete = true
			cyan_concrete = true
			gray_concrete = true
			green_concrete = true
			light_blue_concrete = true
			lime_concrete = true
			magenta_concrete = true
			orange_concrete = true
			pink_concrete = true
			purple_concrete = true
			red_concrete = true
			light_gray_concrete = true
			white_concrete = true
			yellow_concrete = true
			black_wool = true
			blue_wool = true
			brown_wool = true
			cyan_wool = true
			gray_wool = true
			green_wool = true
			light_blue_wool = true
			lime_wool = true
			magenta_wool = true
			orange_wool = true
			pink_wool = true
			purple_wool = true
			red_wool = true
			light_gray_wool = true
			white_wool = true
			yellow_wool = true
			white_terracotta = true
			orange_terracotta = true
			magenta_terracotta = true
			light_blue_terracotta = true
			yellow_terracotta = true
			lime_terracotta = true
			pink_terracotta = true
			gray_terracotta = true
			light_gray_terracotta = true
			cyan_terracotta = true
			purple_terracotta = true
			blue_terracotta = true
			brown_terracotta = true
			green_terracotta = true
			red_terracotta = true
			black_terracotta = true
			terracotta = true
			glass = true
			mushroom_stem = true
			red_mushroom = true
			brown_mushroom = true
			calcite = true
			tuff = true
			smooth_basalt = true
			cracked_nether_bricks = true
			cracked_deepslate_bricks = true
			cracked_deepslate_tiles = true
			sculk = true
			mud = true
			packed_mud = true
			reinforced_deepslate = true
			ochre_froglight = true
			pearlescent_froglight = true
			verdant_froglight = true
			deepslate = true
			rooted_dirt = true
			muddy_mangrove_roots = true
			cracked_polished_blackstone_bricks = true
			shroomlight = true
			gilded_blackstone = true
			soul_sand = true
			soul_soil = true
			packed_ice = true
			blue_ice = true

		[types.cut_block_type.cataclysm]
			polished_end_stone = true
			obsidian_brick = true
			chorus = true
			frosted_stone_brick = true
			stone_tile = true
			azure_seastone = true
			azure_seastone_brick = true
			polished_azure_seastone = true

		[types.cut_block_type.outer_end]
			azure = true
			violite = true
			violite_brick = true
			mossy_violite_brick = true
			violite_tile = true
			mossy_violite_tile = true

		[types.cut_block_type.mobcompack]
			polished_rose_quartz_bricks = true

		[types.cut_block_type.mynethersdelight]
			powdery = true
			powdery_mosaic = true

		[types.cut_block_type.mowziesmobs]
			painted_acacia = true

		[types.cut_block_type.ecologics]
			coconut = true
			seashell_tile = true
			ice_brick = true
			snow_brick = true
			walnut = true
			azalea = true
			flowering_azalea = true

		[types.cut_block_type.bloomingnature]
			larch = true
			baobab = true
			swamp_oak = true
			aspen = true
			fan_palm = true
			fir = true
			swamp_cypress = true
			ebony = true
			chestnut = true
			red_brick = true
			travertin = true
			cobbled_travertin = true
			travertin_brick = true
			mossy_travertin_brick = true
			mossy_cobbled_travertin = true
			laterit = true
			cobbled_laterit = true
			laterit_brick = true
			mossy_laterit_brick = true
			mossy_cobbled_laterit = true
			slate = true
			cobbled_slate = true
			slate_brick = true
			mossy_slate_brick = true
			mossy_cobbled_slate = true
			mossy_slate = true
			mossy_travertin = true
			mossy_laterit = true
			mushroom_brick = true
			brown_mushroom_brick = true
			cactus = true

		[types.cut_block_type.sullysmod]
			rough_jade_brick = true
			jade_brick = true
			amber_brick = true
			petrified = true

		[types.cut_block_type.savage_and_ravage]
			gloomy_tile = true

		[types.cut_block_type.endergetic]
			poise = true
			eumus_brick = true

		[types.cut_block_type.environmental]
			dirt_brick = true
			dirt_tile = true
			smooth_mud = true
			grass_thatch = true
			cattail_thatch = true
			duckweed_thatch = true
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.cut_block_type.upgrade_aquatic]
			beachgrass_thatch = true
			luminous_prismarine = true
			tooth_brick = true
			scute_shingle = true
			scute_pavement = true
			coralstone = true
			bubble_coralstone = true
			horn_coralstone = true
			tube_coralstone = true
			brain_coralstone = true
			fire_coralstone = true
			acan_coralstone = true
			finger_coralstone = true
			star_coralstone = true
			moss_coralstone = true
			petal_coralstone = true
			branch_coralstone = true
			rock_coralstone = true
			pillow_coralstone = true
			silk_coralstone = true
			chrome_coralstone = true
			prismarine_coralstone = true
			elder_prismarine_coralstone = true
			dead_coralstone = true
			kelpy_cobblestone = true
			kelpy_stone_brick = true
			kelpy_cobblestone_brick = true
			kelpy_cobblestone_tile = true
			driftwood = true
			river = true

		[types.cut_block_type.neapolitan]
			chocolate_brick = true
			chocolate_tile = true
			frond_thatch = true

		[types.cut_block_type.buzzier_bees]
			honeycomb_brick = true
			honeycomb_tile = true

		[types.cut_block_type.alexscaves]
			galena = true
			galena_brick = true
			limestone = true
			smooth_limestone = true
			pewen = true
			radrock = true
			radrock_brick = true
			cinder_block = true
			abyssmarine = true
			abyssmarine_brick = true
			smooth_bone = true
			guanostone = true
			guanostone_brick = true
			coprolith = true
			smooth_coprolith = true
			thornwood = true
			gingerbread_brick = true
			frosted_gingerbread_brick = true

		[types.cut_block_type.regions_unexplored]
			chalk_brick = true
			chalk = true
			polished_chalk = true
			alpha = true
			baobab = true
			blackwood = true
			blue_bioshroom = true
			brimwood = true
			cobalt = true
			cypress = false
			dead = true
			eucalyptus = true
			green_bioshroom = true
			joshua = true
			kapok = true
			larch = true
			magnolia = true
			maple = true
			mauve = true
			palm = true
			pine = true
			pink_bioshroom = true
			redwood = true
			socotra = true
			willow = true
			yellow_bioshroom = true
			red_painted = true
			orange_painted = true
			yellow_painted = true
			lime_painted = true
			green_painted = true
			cyan_painted = true
			light_blue_painted = true
			blue_painted = true
			purple_painted = true
			magenta_painted = true
			pink_painted = true
			brown_painted = true
			white_painted = true
			light_gray_painted = true
			gray_painted = true
			black_painted = true

		[types.cut_block_type.atmospheric]
			rosewood = true
			morado = true
			ivory_travertine = true
			peach_travertine = true
			persimmon_travertine = true
			saffron_travertine = true
			dolerite = true
			polished_dolerite = true
			arid_sandstone = true
			smooth_arid_sandstone = true
			cut_arid_sandstone = true
			red_arid_sandstone = true
			smooth_red_arid_sandstone = true
			cut_red_arid_sandstone = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true
			carmine_shingle = true
			carmine_pavement = true

		[types.cut_block_type.quark]
			ancient_planks = true
			azalea_planks = true
			blossom_planks = true
			duskbound_block = true
			iron_plate = true
			rusty_iron_plate = true
			midori_block = true
			blue_nether_bricks = true
			sandstone_bricks = true
			red_sandstone_bricks = true
			soul_sandstone_bricks = true
			cobblestone_bricks = true
			mossy_cobblestone_bricks = true
			blackstone_bricks = true
			dirt_bricks = true
			netherrack_bricks = true
			limestone = true
			polished_limestone = true
			jasper = true
			polished_jasper = true
			shale = true
			polished_shale = true
			myalite = true
			polished_myalite = true
			permafrost = true
			permafrost_bricks = true
			raw_iron_bricks = true
			raw_gold_bricks = true
			raw_copper_bricks = true
			shingles = true
			white_shingles = true
			orange_shingles = true
			magenta_shingles = true
			light_blue_shingles = true
			yellow_shingles = true
			lime_shingles = true
			pink_shingles = true
			gray_shingles = true
			light_gray_shingles = true
			cyan_shingles = true
			purple_shingles = true
			blue_shingles = true
			brown_shingles = true
			green_shingles = true
			red_shingles = true
			black_shingles = true
			soul_sandstone = true
			cut_soul_sandstone = true
			smooth_soul_sandstone = true
			thatch = true
			calcite = true
			polished_calcite = true
			dripstone_block = true
			polished_dripstone = true
			tuff = true
			polished_tuff = true
			granite_bricks = true
			diorite_bricks = true
			andesite_bricks = true
			calcite_bricks = true
			dripstone_bricks = true
			tuff_bricks = true
			limestone_bricks = true
			jasper_bricks = true
			shale_bricks = true
			myalite_bricks = true

		[types.cut_block_type.supplementaries]
			lapis_bricks = true
			ash_bricks = true
			stone_tile = true
			blackstone_tile = true
			fine_wood = true

		[types.cut_block_type.etcetera]
			leveled_stone = true

		[types.cut_block_type.yungscavebiomes]
			smooth_ancient_sandstone = true
			cut_ancient_sandstone = true
			ancient_sandstone = true

		[types.cut_block_type.bbb]
			polished_stone = true
			stone_tile = true

		[types.cut_block_type.netherexp]
			soul_slate = true
			soul_slate_brick = true
			soul_slate_tile = true
			smooth_netherrack = true
			netherrack_brick = true
			basalt = true
			polished_basalt = true
			polished_basalt_brick = true
			claret = true
			smokestalk = true
			silica_sandstone = true
			cut_silica_sandstone = true
			smooth_silica_sandstone = true
			blue_nether_brick = true
			stacked_bone = true
			stacked_wither_bone = true
			yellow_nether_brick = true

		[types.cut_block_type.exquisito]
			warzipan_brick = true
			dessert_checkered_brick = true
			carmotine_brick = true

	[types.stone_type]

		[types.stone_type.immersive_weathering]
			snowy_stone = true
			sandy_stone = true
			mossy_stone = true

		[types.stone_type.biomesoplenty]
			brimstone = true

		[types.stone_type.bloomingnature]
			travertin = true
			laterit = true
			slate = true

		[types.stone_type.alexscaves]
			galena = true
			radrock = true
			abyssmarine = true
			guanostone = true
			limestone = true

		[types.stone_type.regions_unexplored]
			chalk = true

		[types.stone_type.quark]
			soul_sandstone = true
			permafrost = true
			limestone = true
			jasper = true
			shale = true
			myalite = true

		[types.stone_type.supplementaries]
			ash = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.another_furniture]
			flower_box = true
			shelf = true
			shutter = true
			bench = true
			table = true
			drawer = true
			chair = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			vertical_slab = true

		[entries.wood_type.regions_unexplored]
			branch = true

		[entries.wood_type.lolmct]
			crafting_table = true

		[entries.wood_type.absentbydesign]
			wall_stripped_log = true
			wall_log = true
			wall_planks = true
			fence_log = true

		[entries.wood_type.bbb]
			frame = true
			trim = true
			ladder = true
			layer = true
			wall = true
			beam_stairs = true
			beam_slab = true
			support = true
			lantern = true
			pallet = true
			beam = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.regions_unexplored]
			shrub = true

