
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.habitat]
			fairy_ring_mushroom = true

		[types.wood_type.ecologics]
			flowering_azalea = false
			azalea = false
			coconut = true
			walnut = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = false
			mahogany = true
			jacaranda = true
			palm = false
			willow = false
			dead = false
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.phantasm]
			pream = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.outer_end]
			azure = true

		[types.wood_type.spawn]
			rotten = true

		[types.wood_type.endergetic]
			poise = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.regions_unexplored]
			alpha = false
			baobab = true
			blackwood = true
			blue_bioshroom = true
			brimwood = true
			cobalt = true
			cypress = true
			dead = false
			eucalyptus = true
			green_bioshroom = true
			joshua = true
			kapok = false
			larch = false
			magnolia = true
			maple = true
			mauve = true
			palm = false
			pine = false
			pink_bioshroom = true
			redwood = true
			socotra = true
			willow = false
			yellow_bioshroom = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.wood_type.valhelsia_structures]
			lapidified_jungle = true

	[types.leaves_type]

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			maple = false
			orange_autumn = true
			yellow_autumn = true
			rainbow_birch = true
			snowblossom = true
			fir = true
			redwood = false
			mahogany = true
			jacaranda = true
			palm = false
			willow = false
			dead = false
			magic = true
			umbran = true
			hellbark = true

		[types.leaves_type.regions_unexplored]
			bamboo = true
			golden_larch = false
			alpha = false
			apple_oak = true
			baobab = true
			blackwood = true
			magnolia = true
			cypress = true
			dead = true
			dead_pine = false
			eucalyptus = true
			flowering = true
			kapok = false
			larch = false
			maple = true
			mauve = true
			orange_maple = true
			palm = false
			pine = false
			blue_magnolia = true
			pink_magnolia = true
			redwood = true
			red_maple = true
			brimwood = true
			enchanted_birch = true
			small_oak = true
			silver_birch = true
			socotra = true
			white_magnolia = true
			willow = false
			ashen = true

		[types.leaves_type.phantasm]
			pream = true

		[types.leaves_type.outer_end]
			azure = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.environmental]
			hibiscus = true
			willow = true
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

	[types.cake]

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.cake.seasonals]
			pumpkin_cake = true
			sweet_berry_cake = true
			beetroot_cake = true

		[types.cake.mynethersdelight]
			magma_cake = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.another_furniture]
			flower_box = true
			shelf = true
			shutter = true
			bench = true
			table = true
			drawer = true
			chair = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true

		[entries.wood_type.hearth_and_home]
			lattice = true
			parquet = true
			vertical_trim = true
			trim = true
			sanded_wood = true

		[entries.wood_type.regions_unexplored]
			branch = true

		[entries.wood_type.valhelsia_structures]
			stripped_post = false
			cut_post = false
			post = false
			cut_stripped_post = false

		[entries.wood_type.lolmct]
			crafting_table = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

