# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, color and entities values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "cataclysm:coral_golem",
    "alexsmobs:snow_leopard",
    "born_in_chaos_v1:siamese_skeletonsleft",
    "galosphere:berserker",
    "irons_spellbooks:archevoker",
    "born_in_chaos_v1:siamese_skeletonsright",
    "endermanoverhaul:flower_fields_enderman",
    "irons_spellbooks:catacombs_zombie",
    "endermanoverhaul:desert_enderman",
    "savage_and_ravage:trickster",
    "alexsmobs:endergrade",
    "minecraft:horse",
    "missingwilds:firefly_swarm",
    "enemyexpansion:meature",
    "born_in_chaos_v1:lifestealer",
    "minecraft:llama",
    "alexscaves:underzealot",
    "cataclysm:ender_guardian",
    "alexsmobs:skreecher",
    "cataclysm:deepling_warlock",
    "minecraft:tadpole",
    "bygonenether:piglin_hunter",
    "upgrade_aquatic:immortal_jellyfish",
    "environmental:yak",
    "alexscaves:corrodent",
    "bygonenether:wex",
    "alexsmobs:hammerhead_shark",
    "alexscaves:magnetron",
    "upgrade_aquatic:box_jellyfish",
    "alexsmobs:grizzly_bear",
    "alexsmobs:murmur_head",
    "environmental:duck",
    "enemyexpansion:trollenraged",
    "endergetic:purpoid",
    "bygonenether:warped_enderman",
    "creature_compendium:unseen_grasp",
    "galosphere:spectre",
    "enemyexpansion:troll",
    "minecraft:mooshroom",
    "born_in_chaos_v1:seared_spirit_not_despawn",
    "minecraft:axolotl",
    "irons_spellbooks:summoned_vex",
    "alexsmobs:gorilla",
    "enemyexpansion:vampire",
    "quark:crab",
    "alexsmobs:cosmic_cod",
    "sullysmod:lanternfish",
    "alexscaves:deep_one_mage",
    "endermanoverhaul:hammerhead_pet_enderman",
    "alexsmobs:kangaroo",
    "born_in_chaos_v1:corpse_fish",
    "born_in_chaos_v1:supreme_bonescaller_stage_2",
    "creeperoverhaul:spruce_creeper",
    "ecologics:coconut_crab",
    "raided:incinerator",
    "alexsmobs:hummingbird",
    "sullysmod:copper_golem",
    "alexscaves:deep_one",
    "alexsmobs:crow",
    "alexsmobs:guster",
    "born_in_chaos_v1:bone_imp",
    "enemyexpansion:vampflyer",
    "born_in_chaos_v1:nightmare_stalker",
    "irons_spellbooks:magehunter_vindicator",
    "netherdepthsupgrade:obsidianfish",
    "cataclysm:koboleton",
    "minecraft:chicken",
    "alexsmobs:giant_squid",
    "minecraft:zombie",
    "alexsmobs:emu",
    "born_in_chaos_v1:siamese_skeletons",
    "buzzier_bees:moobloom",
    "queen_bee:queen_bee",
    "alexsmobs:flutter",
    "minecraft:hoglin",
    "netherdepthsupgrade:eyeball_fish",
    "born_in_chaos_v1:lords_felsteed",
    "minecraft:zombified_piglin",
    "habitat:pooka",
    "minecraft:sheep",
    "quark:foxhound",
    "born_in_chaos_v1:lord_pumpkinhead_withouta_horse",
    "netherdepthsupgrade:wither_bonefish",
    "alexsmobs:bone_serpent_part",
    "alexsmobs:raccoon",
    "born_in_chaos_v1:fallen_chaos_knight",
    "minecraft:ravager",
    "difficult_spawners:evil_spirit",
    "alexsmobs:bone_serpent",
    "enemyexpansion:flutterfly",
    "spawn:hamster",
    "crittersandcompanions:dragonfly",
    "born_in_chaos_v1:riding_lords_felsteed",
    "alexsmobs:mudskipper",
    "alexsmobs:crimson_mosquito",
    "creeperoverhaul:beach_creeper",
    "endergetic:booflo_baby",
    "creeperoverhaul:hills_creeper",
    "alexsmobs:jerboa",
    "upgrade_aquatic:perch",
    "crittersandcompanions:otter",
    "born_in_chaos_v1:bloody_gadfly",
    "piglinproliferation:piglin_traveler",
    "endermanoverhaul:spirit",
    "alexsmobs:comb_jelly",
    "born_in_chaos_v1:skeleton_thrasher",
    "creeperoverhaul:bamboo_creeper",
    "born_in_chaos_v1:controlled_spiritual_assistant",
    "alexsmobs:enderiophage",
    "alexsmobs:sunbird",
    "minecraft:cat",
    "minecraft:tropical_fish",
    "cataclysm:the_prowler",
    "alexscaves:gloomoth",
    "bygonenether:wither_skeleton_horse",
    "spawn:tuna",
    "alexscaves:vesper",
    "alexscaves:lanternfish",
    "endergetic:puff_bug",
    "minecraft:zombie_villager",
    "environmental:zebra",
    "born_in_chaos_v1:dire_hound_leader",
    "alexsmobs:froststalker",
    "minecraft:giant",
    "enemyexpansion:botfly",
    "alexsmobs:lobster",
    "mowziesmobs:lantern",
    "alexsmobs:seagull",
    "endermanoverhaul:end_enderman",
    "alexscaves:brainiac",
    "endermanoverhaul:soulsand_valley_enderman",
    "etcetera:chapple",
    "upgrade_aquatic:thrasher",
    "spawn:seahorse",
    "creeperoverhaul:cave_creeper",
    "minecraft:husk",
    "bosses_of_mass_destruction:gauntlet",
    "born_in_chaos_v1:firelight_not_despawn",
    "born_in_chaos_v1:door_knight",
    "mowziesmobs:umvuthana",
    "savage_and_ravage:skeleton_villager",
    "creature_compendium:moleman",
    "alexscaves:luxtructosaurus",
    "deeperdarker:sculk_centipede",
    "minecraft:donkey",
    "endertrigon:baby_ender_dragon",
    "mowziesmobs:umvuthana_crane_player",
    "cataclysm:the_leviathan",
    "minecraft:piglin_brute",
    "cataclysm:the_baby_leviathan",
    "galosphere:sparkle",
    "deeperdarker:stalker",
    "cataclysm:deepling_brute",
    "bosses_of_mass_destruction:void_blossom",
    "alexsmobs:frilled_shark",
    "born_in_chaos_v1:pumpkin_spirit",
    "sullysmod:tortoise",
    "alexsmobs:bald_eagle",
    "endermanoverhaul:scarab",
    "enemyexpansion:tarantula",
    "alexsmobs:blobfish",
    "ecologics:squirrel",
    "born_in_chaos_v1:infernal_spirit",
    "environmental:slabfish",
    "upgrade_aquatic:great_thrasher",
    "alexsmobs:void_worm",
    "born_in_chaos_v1:sir_pumpkinhead_without_horse",
    "minecraft:parrot",
    "irons_spellbooks:apothecarist",
    "alexsmobs:centipede_head",
    "cataclysm:the_watcher",
    "enemyexpansion:wasp",
    "enemyexpansion:intruder",
    "creeperoverhaul:desert_creeper",
    "alexsmobs:banana_slug",
    "savage_and_ravage:griefer",
    "savage_and_ravage:iceologer",
    "alexsmobs:bunfungus",
    "minecraft:mule",
    "minecraft:vindicator",
    "alexsmobs:flying_fish",
    "crittersandcompanions:leaf_insect",
    "creeperoverhaul:mushroom_creeper",
    "quark:forgotten",
    "cataclysm:nameless_sorcerer",
    "cataclysm:endermaptera",
    "irons_spellbooks:debug_wizard",
    "endergetic:booflo_adolescent",
    "cataclysm:lionfish",
    "born_in_chaos_v1:corpse_fly",
    "cataclysm:coralssus",
    "irons_spellbooks:spectral_steed",
    "creeperoverhaul:badlands_creeper",
    "creeperoverhaul:snowy_creeper",
    "netherdepthsupgrade:glowdine",
    "cataclysm:the_harbinger",
    "alexsmobs:terrapin",
    "upgrade_aquatic:nautilus",
    "piglinproliferation:piglin_alchemist",
    "atmospheric:cochineal",
    "outer_end:himmelite",
    "minecraft:pig",
    "born_in_chaos_v1:restless_spirit",
    "alexsmobs:alligator_snapping_turtle",
    "creeperoverhaul:swamp_creeper",
    "bosses_of_mass_destruction:obsidilith",
    "endermanoverhaul:crimson_forest_enderman",
    "minecraft:cod",
    "alexsmobs:platypus",
    "minecraft:cow",
    "alexsmobs:rocky_roller",
    "born_in_chaos_v1:scarlet_persecutor",
    "born_in_chaos_v1:phantom_creeper_copy",
    "alexsmobs:soul_vulture",
    "alexsmobs:blue_jay",
    "minecraft:salmon",
    "cataclysm:ignis",
    "crittersandcompanions:dumbo_octopus",
    "enemyexpansion:scorpion",
    "born_in_chaos_v1:seared_spirit",
    "mowziesmobs:naga",
    "netherdepthsupgrade:fortressgrouper",
    "alexsmobs:anteater",
    "alexsmobs:rain_frog",
    "spawn:angler_fish",
    "mowziesmobs:ferrous_wroughtnaut",
    "born_in_chaos_v1:zombie_clown",
    "minecraft:rabbit",
    "minecraft:pillager",
    "born_in_chaos_v1:decaying_zombie_not_despawn",
    "minecraft:zoglin",
    "savage_and_ravage:creepie",
    "born_in_chaos_v1:zombie_bruiser",
    "alexsmobs:leafcutter_ant",
    "born_in_chaos_v1:lord_the_headless",
    "variantsandventures:verdant",
    "enemyexpansion:starved",
    "born_in_chaos_v1:diamond_termite",
    "creeperoverhaul:jungle_creeper",
    "cataclysm:deepling_priest",
    "irons_spellbooks:cryomancer",
    "enemyexpansion:invisicreeper",
    "deeperdarker:shriek_worm",
    "cataclysm:ignited_revenant",
    "spelunkers_charm:sound_entity",
    "alexsmobs:gazelle",
    "minecraft:sniffer",
    "endermanoverhaul:windswept_hills_enderman",
    "alexscaves:watcher",
    "endermanoverhaul:end_islands_enderman",
    "born_in_chaos_v1:missioner",
    "deeperdarker:sculk_snapper",
    "mowziesmobs:umvuthana_follower_player",
    "cataclysm:modern_remnant",
    "born_in_chaos_v1:supreme_bonescaller_not_despawn",
    "endermanoverhaul:warped_forest_enderman",
    "alexsmobs:seal",
    "environmental:deer",
    "enemyexpansion:goblin",
    "alexsmobs:roadrunner",
    "alexsmobs:laviathan",
    "minecraft:trader_llama",
    "irons_spellbooks:necromancer",
    "born_in_chaos_v1:riding_felsteed",
    "born_in_chaos_v1:pumpkin_bomb",
    "outer_end:sinker",
    "born_in_chaos_v1:skeleton_demoman",
    "alexsmobs:maned_wolf",
    "minecraft:dolphin",
    "neapolitan:plantain_spider",
    "born_in_chaos_v1:supreme_bonescaller",
    "endermanoverhaul:badlands_enderman",
    "alexsmobs:gelada_monkey",
    "alexsmobs:dropbear",
    "alexsmobs:tiger",
    "crittersandcompanions:jumping_spider",
    "buzzier_bees:grizzly_bear",
    "outer_end:entombed",
    "enemyexpansion:crawler",
    "minecraft:bee",
    "alexsmobs:devils_hole_pupfish",
    "minecraft:illusioner",
    "born_in_chaos_v1:dread_hound",
    "born_in_chaos_v1:skeleton_thrasher_not_despawn",
    "endermanoverhaul:axolotl_pet_enderman",
    "takesapillage:skirmisher",
    "alexsmobs:bison",
    "mowziesmobs:foliaath",
    "mowziesmobs:frostmaw",
    "outer_end:purpur_golem",
    "minecraft:drowned",
    "creature_compendium:netherite_forge",
    "born_in_chaos_v1:bone_imp_minion",
    "environmental:tapir",
    "alexsmobs:tusklin",
    "born_in_chaos_v1:senor_pumpkin",
    "alexsmobs:underminer",
    "sullysmod:bouldering_zombie",
    "minecraft:wandering_trader",
    "environmental:reindeer",
    "born_in_chaos_v1:glutton_fish",
    "netherdepthsupgrade:lava_pufferfish",
    "netherdepthsupgrade:blazefish",
    "netherdepthsupgrade:bonefish",
    "crittersandcompanions:sea_bunny",
    "cataclysm:netherite_monstrosity",
    "endergetic:glider_eetle",
    "cataclysm:wadjet",
    "upgrade_aquatic:flare",
    "alexscaves:boundroid",
    "spawn:ant",
    "mowziesmobs:umvuthana_raptor",
    "crittersandcompanions:red_panda",
    "endermanoverhaul:cave_enderman",
    "endermanoverhaul:mushroom_fields_enderman",
    "minecraft:pufferfish",
    "minecraft:fox",
    "enemyexpansion:ladybug",
    "born_in_chaos_v1:firelight",
    "mowziesmobs:umvuthana_crane",
    "alexsmobs:warped_toad",
    "born_in_chaos_v1:mr_pumpkin_controlled",
    "enemyexpansion:silverqueenbodiless",
    "alexsmobs:cockroach",
    "creeperoverhaul:savannah_creeper",
    "born_in_chaos_v1:lord_pumpkinhead",
    "born_in_chaos_v1:zombie_lumberjack",
    "neapolitan:chimpanzee",
    "endermanoverhaul:pet_enderman",
    "alexscaves:ferrouslime",
    "cataclysm:deepling_angler",
    "alexsmobs:capuchin_monkey",
    "minecraft:polar_bear",
    "endermanoverhaul:ice_spikes_enderman",
    "minecraft:turtle",
    "born_in_chaos_v1:lord_pumpkinhead_head",
    "variantsandventures:gelid",
    "netherdepthsupgrade:searing_cod",
    "quark:wraith",
    "alexsmobs:rattlesnake",
    "born_in_chaos_v1:zombie_fisherman",
    "endergetic:brood_eetle",
    "born_in_chaos_v1:controlled_baby_skeleton",
    "enemyexpansion:direwolf",
    "goodending:woodpecker",
    "deeperdarker:sculk_leech",
    "alexsmobs:potoo",
    "alexsmobs:fly",
    "alexscaves:trilocaris",
    "irons_spellbooks:dead_king",
    "quark:shiba",
    "alexsmobs:straddler",
    "born_in_chaos_v1:door_knight_not_despawn",
    "alexsmobs:sea_bear",
    "born_in_chaos_v1:spirit_guide",
    "born_in_chaos_v1:dread_hound_not_despawn",
    "alexscaves:nucleeper",
    "alexscaves:hullbreaker",
    "born_in_chaos_v1:zombie_clown_not_despawn",
    "mowziesmobs:umvuthana_follower_raptor",
    "cataclysm:ender_golem",
    "alexsmobs:sugar_glider",
    "supplementaries:red_merchant",
    "endermanoverhaul:swamp_enderman",
    "sullysmod:jungle_spider",
    "kiwiboi:kiwi",
    "netherdepthsupgrade:magmacubefish",
    "raided:electromancer",
    "savage_and_ravage:executioner",
    "alexsmobs:orca",
    "born_in_chaos_v1:spiritof_chaos",
    "irons_spellbooks:priest",
    "born_in_chaos_v1:sir_pumpkinhead",
    "minecraft:bat",
    "alexsmobs:cosmaw",
    "bygonenether:corpor",
    "born_in_chaos_v1:decrepit_skeleton",
    "born_in_chaos_v1:bonescaller_not_despawn",
    "alexsmobs:skunk",
    "born_in_chaos_v1:baby_skeleton",
    "born_in_chaos_v1:lifestealer_true_form",
    "cataclysm:deepling",
    "environmental:koi",
    "alexsmobs:tasmanian_devil",
    "born_in_chaos_v1:thornshell_crab",
    "outer_end:stalker",
    "cataclysm:ancient_remnant",
    "alexsmobs:stradpole",
    "ecologics:penguin",
    "endermanoverhaul:savanna_enderman",
    "minecraft:panda",
    "endermanoverhaul:coral_enderman",
    "alexsmobs:moose",
    "alexsmobs:shoebill",
    "alexsmobs:farseer",
    "cataclysm:amethyst_crab",
    "born_in_chaos_v1:maggot",
    "upgrade_aquatic:goose",
    "alexsmobs:warped_mosco",
    "galosphere:preserved",
    "endermanoverhaul:dark_oak_enderman",
    "alexsmobs:komodo_dragon",
    "born_in_chaos_v1:felsteed",
    "alexscaves:forsaken",
    "born_in_chaos_v1:spirit_guide_assistant",
    "alexscaves:mine_guardian",
    "born_in_chaos_v1:baby_skeleton_minion",
    "cataclysm:ignited_berserker",
    "quark:stoneling",
    "irons_spellbooks:summoned_polar_bear",
    "alexsmobs:crocodile",
    "alexscaves:teletor",
    "quark:toretoise",
    "irons_spellbooks:cultist",
    "alexsmobs:triops",
    "alexsmobs:rhinoceros",
    "born_in_chaos_v1:mr_pumpkin",
    "galosphere:specterpillar",
    "enemyexpansion:vampbiter",
    "alexsmobs:mimicube",
    "born_in_chaos_v1:phantom_creeper",
    "bygonenether:wither_skeleton_knight",
    "enemyexpansion:goblin_fear",
    "minecraft:frog",
    "spawn:snail",
    "crittersandcompanions:shima_enaga",
    "enemyexpansion:drone",
    "alexsmobs:mimic_octopus",
    "alexsmobs:void_worm_part",
    "upgrade_aquatic:cassiopea_jellyfish",
    "enemyexpansion:huntsman",
    "minecraft:evoker",
    "born_in_chaos_v1:barrel_zombie",
    "phantasm:crystie",
    "alexsmobs:tarantula_hawk",
    "crittersandcompanions:ferret",
    "alexsmobs:cachalot_whale",
    "variantsandventures:thicket",
    "endermanoverhaul:nether_wastes_enderman",
    "creeperoverhaul:ocean_creeper",
    "born_in_chaos_v1:decaying_zombie",
    "alexscaves:gammaroach",
    "creeperoverhaul:dark_oak_creeper",
    "astemirlib:jas",
    "upgrade_aquatic:pike",
    "spelunkers_charm:tremor_handler",
    "takesapillage:legioner",
    "goodending:firefly_swarm",
    "alexscaves:notor",
    "bosses_of_mass_destruction:lich",
    "alexsmobs:anaconda",
    "born_in_chaos_v1:phantom_bomb_entity",
    "irons_spellbooks:summoned_zombie",
    "mowziesmobs:grottol",
    "creature_compendium:unseen_hand",
    "mowziesmobs:baby_foliaath",
    "born_in_chaos_v1:swarmer",
    "minecraft:goat",
    "enemyexpansion:slugger",
    "alexsmobs:mantis_shrimp",
    "netherdepthsupgrade:soulsucker",
    "raided:necromancer",
    "bygonenether:wraither",
    "born_in_chaos_v1:pumpkinhead",
    "endermanoverhaul:snowy_enderman",
    "mowziesmobs:umvuthi",
    "alexscaves:radgill",
    "bygonenether:piglin_prisoner",
    "alexsmobs:toucan",
    "upgrade_aquatic:lionfish",
    "habitat:passerine",
    "born_in_chaos_v1:dark_vortex",
    "outer_end:spectrafly",
    "enemyexpansion:silverqueen",
    "raided:inquisitor",
    "irons_spellbooks:pyromancer",
    "alexsmobs:murmur",
    "goodending:marsh",
    "creeperoverhaul:dripstone_creeper",
    "irons_spellbooks:summoned_skeleton",
    "raided:savager",
    "alexsmobs:mungus",
    "crittersandcompanions:koi_fish",
    "alexsmobs:caiman",
    "irons_spellbooks:citadel_keeper",
    "alexsmobs:spectre",
    "cataclysm:kobolediator",
    "alexsmobs:catfish",
    "endergetic:charger_eetle",
    "minecraft:piglin",
    "alexsmobs:skelewag",
    "enemyexpansion:equestrian",
    "born_in_chaos_v1:sir_the_headless",
    "takesapillage:archer",
    "enemyexpansion:sprinter",
    "alexscaves:boundroid_winch",
    "alexscaves:deep_one_knight",
    "alexsmobs:elephant",
    "minecraft:zombie_horse",
    "minecraft:camel",
    "born_in_chaos_v1:bonescaller",
    "deeperdarker:shattered",
    "endergetic:booflo",
    "minecraft:ocelot",
    "minecraft:wolf",
    "enemyexpansion:faller"
]
