
["No Startup Messages"]
	#Enable No Startup Messages module
	noStartupMessagesEnabled = true
	#A list of word sequences that if contained in a message will be stopped.
	noStartupMessagesMessages = ["lost -0.0 difficulty", "gained 0.00 difficulty"]

[Recipes]
	#Disable recipe advancements
	disableRecipeAdvancements = true

