
#Boss Themed Weapons
[boss_weapons]

	[boss_weapons.abyssal_tidecaller]
		#Durability
		#Range: > 1
		durability = 2500
		#Damage
		#Range: 0.0 ~ 100.0
		damage = 25.0
		#Attack Speed
		#Range: -5.0 ~ 5.0
		attack_speed = -3.0
		#Eldritch Spell Power, MULTIPLY_TOTAL
		#Range: 0.0 ~ 1.0
		eldritch_spell_power = 0.15
		#Ender Spell Power, MULTIPLY_TOTAL
		#Range: 0.0 ~ 1.0
		ender_spell_power = 0.1

	[boss_weapons.flames_of_eldritch]
		#Durability
		#Range: > 1
		durability = 3000
		#Damage
		#Range: 0.0 ~ 100.0
		damage = 21.0
		#Attack Speed
		#Range: -5.0 ~ 5.0
		attack_speed = -2.6
		#Eldritch Spell Power, MULTIPLY_TOTAL
		#Range: 0.0 ~ 1.0
		eldritch_spell_power = 0.05
		#Fire Spell Power, MULTIPLY_TOTAL
		#Range: 0.0 ~ 1.0
		fire_spell_power = 0.2

	[boss_weapons.harbingers_wrath]
		#Durability
		#Range: > 1
		durability = 2500
		#Damage
		#Range: 0.0 ~ 100.0
		damage = 21.0
		#Attack Speed
		#Range: -5.0 ~ 5.0
		attack_speed = -2.8
		#Lightning Spell Power, MULTIPLY_TOTAL
		#Range: 0.0 ~ 1.0
		lightning_spell_power = 0.2

	[boss_weapons.scourge_of_the_sands]
		#Durability
		#Range: > 1
		durability = 2500
		#Damage
		#Range: 0.0 ~ 100.0
		damage = 17.0
		#Attack Speed
		#Range: -5.0 ~ 5.0
		attack_speed = -2.4
		#Evocation Spell Power, MULTIPLY_TOTAL
		#Range: 0.0 ~ 1.0
		evocation_spell_power = 0.1
		#Nature Spell Power, MULTIPLY_TOTAL
		#Range: 0.0 ~ 1.0
		nature_spell_power = 0.1

	[boss_weapons.thorns_of_oblivion]
		#Durability
		#Range: > 1
		durability = 2000
		#Damage
		#Range: 0.0 ~ 100.0
		damage = 14.0
		#Attack Speed
		#Range: -5.0 ~ 5.0
		attack_speed = -2.4
		#Nature Spell Power, MULTIPLY_TOTAL
		#Range: 0.0 ~ 1.0
		nature_spell_power = 0.05
		#Ender Spell Power, MULTIPLY_TOTAL
		#Range: 0.0 ~ 1.0
		ender_spell_power = 0.05

#General Weapon Configs
[weapons]

	[weapons.blazegrip_scimitar]
		#Durability
		#Range: > 1
		durability = 2000
		#Damage
		#Range: 0.0 ~ 100.0
		damage = 19.0
		#Attack Speed
		#Range: -5.0 ~ 5.0
		attack_speed = -2.8
		#Fire Damage
		#Range: 0.0 ~ 10.0
		fire_damage = 2.0
		#Fire Spell Power, MULTIPLY_TOTAL
		#Range: 0.0 ~ 1.0
		fire_spell_power = 0.1

	[weapons.bloodbound_carnage]
		#Durability
		#Range: > 1
		durability = 2000
		#Damage
		#Range: 0.0 ~ 100.0
		damage = 19.0
		#Attack Speed
		#Range: -5.0 ~ 5.0
		attack_speed = -2.5
		#Blood Spell Power, MULTIPLY_TOTAL
		#Range: 0.0 ~ 1.0
		blood_spell_power = 0.15

	[weapons.celestial_edge]
		#Durability
		#Range: > 1
		durability = 2000
		#Damage
		#Range: 0.0 ~ 100.0
		damage = 19.0
		#Attack Speed
		#Range: -5.0 ~ 5.0
		attack_speed = -2.5
		#Holy Spell Power, MULTIPLY_TOTAL
		#Range: 0.0 ~ 1.0
		holy_spell_power = 0.1

